/**
 * Copyright (C) 2011 Paul Wortmann, PhysHex Games, www.physhexgames.co.nr
 * This file is part of "Frost And Flame"
 *
 * "Frost And Flame" is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * "Frost And Flame" is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with "Frost And Flame" If not, see <http://www.gnu.org/licenses/>.
 *
 * @author  Paul Wortmann
 * @email   physhex@gmail.com
 * @website www.physhexgames.co.nr
 * @license GPL V3
 * @date 2011-11-11
 */

#include "menu_system.hpp"
#include "game.hpp"
#include "core/core.hpp"
#include "load_resources.hpp"

extern  game_class               game;
extern  sound_type               sound;
extern  music_type               music;
extern  texture_type             texture;
extern  font_type                font;
extern  game_type                game_o;
        menu_type                menu;
        menu_class               main_menu(9);
        menu_class               new_game_menu(9);
        menu_class               save_menu(9);
        menu_class               load_menu(9);
        menu_class               options_menu(9);
        menu_class               game_over_menu(1);
        menu_class               pause_menu(1);

int init_menu   (void)
{
    //------ setup menu background -----------
    game.background.set_data ( 1, 1, 0, 1.0f, 0.0f, 0.0010f, 0.00065f, texture.background_01.ref_number);
    game.background.set_data ( 2, 1, 1, 0.0f, 1.0f, 0.0000f, 0.00000f, texture.background_00.ref_number);
    game.background.set_movement_type(FRONT_SCROLL);
    //------ setup "main" menu -----------
    main_menu.set_menu_title(game_o.language.text.main_menu);
    main_menu.set_keyboard_delay(16);
    main_menu.set_mouse_delay(24);
    main_menu.set_pos(0.0f,-0.1f,0.001f);
    main_menu.set_size(0.8f,1.7f);
    main_menu.set_menu_font(1);
    main_menu.set_image_background(texture.background_02.ref_number);
    main_menu.set_button_zoom(true,0.04f,0.005f);
    main_menu.set_button_images(texture.button_normal.ref_number,texture.button_highlighted.ref_number,texture.button_disabled.ref_number,texture.button_disabled.ref_number,texture.selection_box.ref_number,texture.slider_button_normal.ref_number,texture.slider_button_highlighted.ref_number,texture.arrow_button_normal.ref_number,texture.arrow_button_highlighted.ref_number,texture.arrow_button_disabled.ref_number);
    main_menu.set_color_normal(128,128,128,255);
    main_menu.set_color_highlighted(192,192,192,255);
    main_menu.set_color_disabled(064,064,064,128);
    main_menu.set_number_of_buttons(7);
    main_menu.set_button_data  ( 1,game_o.language.text.new_game);
    main_menu.set_button_data  ( 2,game_o.language.text.load_game);
    main_menu.set_button_data  ( 3,game_o.language.text.save_game);
    main_menu.set_button_data  ( 4,game_o.language.text.resume_game);
    main_menu.set_button_data  ( 5,game_o.language.text.options);
    main_menu.set_button_active( 6,false);
    main_menu.set_button_data  ( 7,game_o.language.text.quit_game);
    main_menu.set_buttons_auto();
    main_menu.set_close_button_data(texture.close_button.ref_number,texture.close_button_highlighted.ref_number);
    main_menu.set_title_data(game_o.language.text.main_menu);//needs to be called last due to size generated by number of buttons etc....
    //------ setup "new game" menu -----------
    new_game_menu.set_menu_title(game_o.language.text.new_game);
    new_game_menu.set_keyboard_delay(16);
    new_game_menu.set_mouse_delay(8);
    new_game_menu.set_pos(0.0f,-0.1f,0.001f);
    new_game_menu.set_size(1.2f,1.0f);
    new_game_menu.set_menu_font(1);
    new_game_menu.set_image_background(texture.background_02.ref_number);
    new_game_menu.set_button_zoom(true,0.04f,0.005f);
    new_game_menu.set_button_images(texture.button_normal.ref_number,texture.button_highlighted.ref_number,texture.button_disabled.ref_number,texture.button_disabled.ref_number,texture.selection_box.ref_number,texture.slider_button_normal.ref_number,texture.slider_button_highlighted.ref_number,texture.arrow_button_normal.ref_number,texture.arrow_button_highlighted.ref_number,texture.arrow_button_disabled.ref_number);
    new_game_menu.set_color_normal(128,128,255,255);
    new_game_menu.set_color_highlighted(192,192,255,255);
    new_game_menu.set_color_disabled(064,064,128,128);
    new_game_menu.set_number_of_buttons(3);
    new_game_menu.set_button_data  ( 1,game_o.language.text.new_game);
    new_game_menu.set_button_active( 2,false);
    new_game_menu.set_button_data  ( 3,game_o.language.text.main_menu);
    new_game_menu.set_buttons_auto();
    new_game_menu.set_close_button_data(texture.close_button.ref_number,texture.close_button_highlighted.ref_number);
    new_game_menu.set_button_arrow_data_auto(1);
    new_game_menu.set_title_data(game_o.language.text.new_game);//needs to be called last due to size generated by number of buttons etc....
    //------ setup "save game" menu -----------
    save_menu.set_menu_title(game_o.language.text.save_menu);
    save_menu.set_keyboard_delay(16);
    save_menu.set_mouse_delay(24);
    save_menu.set_pos(0.0f,-0.1f,0.001f);
    save_menu.set_size(0.8f,1.7f);
    save_menu.set_menu_font(1);
    save_menu.set_image_background(texture.background_02.ref_number);
    save_menu.set_button_zoom(true,0.04f,0.005f);
    save_menu.set_button_images(texture.button_normal.ref_number,texture.button_highlighted.ref_number,texture.button_disabled.ref_number,texture.button_disabled.ref_number,texture.selection_box.ref_number,texture.slider_button_normal.ref_number,texture.slider_button_highlighted.ref_number,texture.arrow_button_normal.ref_number,texture.arrow_button_highlighted.ref_number,texture.arrow_button_disabled.ref_number);
    save_menu.set_color_normal(128,128,255,255);
    save_menu.set_color_highlighted(192,192,255,255);
    save_menu.set_color_disabled(064,064,128,128);
    save_menu.set_number_of_buttons(9);
    save_menu.set_button_data  ( 1,game_o.language.text.save_slot_1);
    save_menu.set_button_data  ( 2,game_o.language.text.save_slot_2);
    save_menu.set_button_data  ( 3,game_o.language.text.save_slot_3);
    save_menu.set_button_data  ( 4,game_o.language.text.save_slot_4);
    save_menu.set_button_data  ( 5,game_o.language.text.save_slot_5);
    save_menu.set_button_data  ( 6,game_o.language.text.save_slot_6);
    save_menu.set_button_data  ( 7,game_o.language.text.save_slot_7);
    save_menu.set_button_active( 8,false);
    save_menu.set_button_data  ( 9,game_o.language.text.main_menu);
    save_menu.set_buttons_auto();
    save_menu.set_close_button_data(texture.close_button.ref_number,texture.close_button_highlighted.ref_number);
    save_menu.set_title_data(game_o.language.text.save_menu);//needs to be called last due to size generated by number of buttons etc....
    //------ setup "load game" menu -----------
    load_menu.set_menu_title(game_o.language.text.load_menu);
    load_menu.set_keyboard_delay(16);
    load_menu.set_mouse_delay(24);
    load_menu.set_pos(0.0f,-0.1f,0.001f);
    load_menu.set_size(0.8f,1.7f);
    load_menu.set_menu_font(1);
    load_menu.set_image_background(texture.background_02.ref_number);
    load_menu.set_button_zoom(true,0.04f,0.005f);
    load_menu.set_button_images(texture.button_normal.ref_number,texture.button_highlighted.ref_number,texture.button_disabled.ref_number,texture.button_disabled.ref_number,texture.selection_box.ref_number,texture.slider_button_normal.ref_number,texture.slider_button_highlighted.ref_number,texture.arrow_button_normal.ref_number,texture.arrow_button_highlighted.ref_number,texture.arrow_button_disabled.ref_number);
    load_menu.set_color_normal(128,128,255,255);
    load_menu.set_color_highlighted(192,192,255,255);
    load_menu.set_color_disabled(064,064,128,128);
    load_menu.set_number_of_buttons(9);
    load_menu.set_button_data  ( 1,game_o.language.text.save_slot_1);
    load_menu.set_button_data  ( 2,game_o.language.text.save_slot_2);
    load_menu.set_button_data  ( 3,game_o.language.text.save_slot_3);
    load_menu.set_button_data  ( 4,game_o.language.text.save_slot_4);
    load_menu.set_button_data  ( 5,game_o.language.text.save_slot_5);
    load_menu.set_button_data  ( 6,game_o.language.text.save_slot_6);
    load_menu.set_button_data  ( 7,game_o.language.text.save_slot_7);
    load_menu.set_button_active( 8,false);
    load_menu.set_button_data  ( 9,game_o.language.text.main_menu);
    load_menu.set_buttons_auto();
    load_menu.set_close_button_data(texture.close_button.ref_number,texture.close_button_highlighted.ref_number);
    load_menu.set_title_data(game_o.language.text.load_menu);//needs to be called last due to size generated by number of buttons etc....
    game.save_01.Assign_File("save/slot_01.sav");
    if (game.save_01.File_Exists()) load_menu.button[1].set_enabled(true);
    else load_menu.button[1].set_enabled(false);
    game.save_02.Assign_File("save/slot_02.sav");
    if (game.save_02.File_Exists()) load_menu.button[2].set_enabled(true);
    else load_menu.button[2].set_enabled(false);
    game.save_03.Assign_File("save/slot_03.sav");
    if (game.save_03.File_Exists()) load_menu.button[3].set_enabled(true);
    else load_menu.button[3].set_enabled(false);
    game.save_04.Assign_File("save/slot_04.sav");
    if (game.save_04.File_Exists()) load_menu.button[4].set_enabled(true);
    else load_menu.button[4].set_enabled(false);
    game.save_05.Assign_File("save/slot_05.sav");
    if (game.save_05.File_Exists()) load_menu.button[5].set_enabled(true);
    else load_menu.button[5].set_enabled(false);
    game.save_06.Assign_File("save/slot_06.sav");
    if (game.save_06.File_Exists()) load_menu.button[6].set_enabled(true);
    else load_menu.button[6].set_enabled(false);
    game.save_07.Assign_File("save/slot_07.sav");
    if (game.save_07.File_Exists()) load_menu.button[7].set_enabled(true);
    else load_menu.button[7].set_enabled(false);
    //------ setup "options" menu -----------
    options_menu.set_menu_title(game_o.language.text.options);
    options_menu.set_keyboard_delay(16);
    options_menu.set_mouse_delay(24);
    options_menu.set_pos(0.0f,-0.1f,0.001f);
    options_menu.set_size(0.8f,1.2f);
    options_menu.set_menu_font(1);
    options_menu.set_image_background(texture.background_02.ref_number);
    options_menu.set_button_zoom(true,0.04f,0.005f);
    options_menu.set_button_images(texture.button_normal.ref_number,texture.button_highlighted.ref_number,texture.button_disabled.ref_number,texture.button_disabled.ref_number,texture.selection_box.ref_number,texture.slider_button_normal.ref_number,texture.slider_button_highlighted.ref_number,texture.arrow_button_normal.ref_number,texture.arrow_button_highlighted.ref_number,texture.arrow_button_disabled.ref_number);
    options_menu.set_toggle_button_images(texture.green_button_highlighted.ref_number,texture.green_button.ref_number,texture.red_button_highlighted.ref_number,texture.red_button.ref_number);
    options_menu.set_color_normal(128,128,255,255);
    options_menu.set_color_highlighted(192,192,255,255);
    options_menu.set_color_disabled(064,064,128,128);
    options_menu.set_number_of_buttons(6);
    options_menu.set_button_data  ( 1,game_o.language.text.sound_volume);
    options_menu.set_button_type  ( 1,SLIDER);
    options_menu.set_button_slider_position(1,game.config.Audio_Sound_Volume);
    options_menu.set_button_slider_position_max(1,128);
    options_menu.set_button_data  ( 2,game_o.language.text.music_volume);
    options_menu.set_button_type  ( 2,SLIDER);
    options_menu.set_button_slider_position(2,game.config.Audio_Music_Volume);
    options_menu.set_button_slider_position_max(2,128);
    options_menu.set_button_data  ( 3,game_o.language.text.screen_resolution);
    options_menu.set_number_of_choices(3,8);
    options_menu.set_number_of_visible_choices(3,5);
    options_menu.set_button_choice_position(3,1);
    options_menu.set_button_disabled_text_label(game_o.language.text.menu_item_unavailable);
    options_menu.set_button_current_choice(3,game.config.Display_resolution);
    options_menu.set_button_choice_data(3, 1,texture.resolution_icon.ref_number,game_o.language.text.res_640_x_480,   true, true);
    options_menu.set_button_choice_data(3, 2,texture.resolution_icon.ref_number,game_o.language.text.res_800_x_600,   true, true);
    options_menu.set_button_choice_data(3, 3,texture.resolution_icon.ref_number,game_o.language.text.res_1024_x_768,  true, true);
    options_menu.set_button_choice_data(3, 4,texture.resolution_icon.ref_number,game_o.language.text.res_1280_x_1024, true, true);
    options_menu.set_button_choice_data(3, 5,texture.resolution_icon.ref_number,game_o.language.text.res_1366_x_768,  true, true);
    options_menu.set_button_choice_data(3, 6,texture.resolution_icon.ref_number,game_o.language.text.res_1440_x_900,  true, true);
    options_menu.set_button_choice_data(3, 7,texture.resolution_icon.ref_number,game_o.language.text.res_1680_x_1050, true, true);
    options_menu.set_button_choice_data(3, 8,texture.resolution_icon.ref_number,game_o.language.text.res_1920_x_1080, true, true);
    options_menu.set_button_data  ( 4,game_o.language.text.full_screen);
    options_menu.set_button_type  ( 4,TOGGLE);
    options_menu.set_button_active( 5,false);
    options_menu.set_button_data  ( 6,game_o.language.text.main_menu);
    options_menu.set_buttons_auto();
    options_menu.set_close_button_data(texture.close_button.ref_number,texture.close_button_highlighted.ref_number);
    options_menu.set_title_data(game_o.language.text.options);//needs to be called last due to size generated by number of buttons etc....
    //------ setup "game over" menu -----------
    game_over_menu.set_menu_title(game_o.language.text.game_over);
    game_over_menu.set_keyboard_delay(16);
    game_over_menu.set_mouse_delay(24);
    game_over_menu.set_pos(0.0f,-0.85f,0.001f);
    game_over_menu.set_size(0.8f,0.2f);
    game_over_menu.set_menu_font(1);
    game_over_menu.set_image_background(texture.background_02.ref_number);
    game_over_menu.set_button_zoom(true,0.04f,0.005f);
    game_over_menu.set_button_images(texture.button_normal.ref_number,texture.button_highlighted.ref_number,texture.button_disabled.ref_number,texture.button_disabled.ref_number,texture.selection_box.ref_number,texture.slider_button_normal.ref_number,texture.slider_button_highlighted.ref_number,texture.arrow_button_normal.ref_number,texture.arrow_button_highlighted.ref_number,texture.arrow_button_disabled.ref_number);
    game_over_menu.set_color_normal(128,128,255,255);
    game_over_menu.set_color_highlighted(192,192,255,255);
    game_over_menu.set_color_disabled(064,064,128,128);
    game_over_menu.set_number_of_buttons(1);
    game_over_menu.set_button_data  ( 1,game_o.language.text.main_menu);
    game_over_menu.set_buttons_auto();
    game_over_menu.set_close_button_data(texture.close_button.ref_number,texture.close_button_highlighted.ref_number);
    game_over_menu.set_title_data(game_o.language.text.game_over);//needs to be called last due to size generated by number of buttons etc....
    //------ setup "pause" menu -----------
    pause_menu.set_menu_title(game_o.language.text.game_paused);
    pause_menu.set_keyboard_delay(16);
    pause_menu.set_mouse_delay(24);
    pause_menu.set_pos(0.0f,-0.85f,0.001f);
    pause_menu.set_size(0.8f,0.2f);
    pause_menu.set_menu_font(1);
    pause_menu.set_image_background(texture.background_02.ref_number);
    pause_menu.set_button_zoom(true,0.04f,0.005f);
    pause_menu.set_button_images(texture.button_normal.ref_number,texture.button_highlighted.ref_number,texture.button_disabled.ref_number,texture.button_disabled.ref_number,texture.selection_box.ref_number,texture.slider_button_normal.ref_number,texture.slider_button_highlighted.ref_number,texture.arrow_button_normal.ref_number,texture.arrow_button_highlighted.ref_number,texture.arrow_button_disabled.ref_number);
    pause_menu.set_color_normal(128,128,255,255);
    pause_menu.set_color_highlighted(192,192,255,255);
    pause_menu.set_color_disabled(064,064,128,128);
    pause_menu.set_number_of_buttons(1);
    pause_menu.set_button_data  ( 1,game_o.language.text.resume_game);
    pause_menu.set_buttons_auto();
    pause_menu.set_close_button_data(texture.close_button.ref_number,texture.close_button_highlighted.ref_number);
    pause_menu.set_title_data(game_o.language.text.game_paused);//needs to be called last due to size generated by number of buttons etc....
    return(0);
};


//---------------------------------------------------------------------------------------
int process_menu(void)
{
    int  activated_button = -1;
    bool set_resolution   = false;
    // ------------------- main menu ------------
    activated_button = -1;
    if (game.menu_level == 1)
    {
        if (game.game_resume) main_menu.button[5].set_enabled(true);
        else main_menu.button[5].set_enabled(false);
        if (game.game_resume) main_menu.button[6].set_enabled(true);
        else main_menu.button[6].set_enabled(false);
        activated_button = main_menu.process();
        switch (activated_button)
        {
            case 1://New Game
                sound.menu_select_00.play();
                game.menu_level = 2;
                game.log.File_Write("Entering 'Star Map' menu.");
            break;
            case 2://Customize Starship
                sound.menu_select_00.play();
                game.menu_level = 3;
                game.log.File_Write("Entering 'Customize Starship' menu.");
            break;
            case 3://Achievements
                sound.menu_select_00.play();
                game.menu_level = 4;
                game.log.File_Write("Entering 'Achievements' menu.");
            break;
            case 4://Load Game
                sound.menu_select_00.play();
                game.menu_level = 5;
                game.log.File_Write("Entering 'Load Game' menu.");
            break;
            case 5://Save Game
                if (game.game_resume)
                {
                    sound.menu_select_00.play();
                    game.menu_level = 6;
                    game.log.File_Write("Entering 'Save Game' menu.");
                }
            break;
            case 6://Resume Game
                if (game.game_resume)
                {
                    sound.menu_select_00.play();
                    game.music_next_track = true;
                    game.game_active      = true;
                    game.menu_active      = false;
                    game.log.File_Write("Resuming Game");
                }
            break;
            case 7://Options
                sound.menu_select_00.play();
                game.menu_level = 7;
                game.log.File_Write("Entering 'Options' menu.");
            break;
            case 8://NA
            break;
            case 9://Quit Game
                sound.menu_select_00.play();
                game.status_quit_active = true;
                game.log.File_Write("User terminating game - 'Quit Game' selected!");
            break;
            case 65533://only move no select.
                sound.menu_move_00.play();
            break;
            case 65534:// escape pressed on keyboard.
                sound.menu_select_00.play();
                game.status_quit_active = true;
                game.io.escape               = false;
                game.log.File_Write("User terminating game - keyboard escape pressed!");
            break;
            case 65535:// close button clicked.
                sound.menu_select_00.play();
                game.status_quit_active = true;
                game.log.File_Write("User terminating game - clicked escape button!");
            break;
            default:
            break;
        };
    };
    // ------------------- New_Game Menu ------------
    activated_button = -1;
    if (game.menu_level == 2)
    {
        activated_button = new_game_menu.process();
        switch (activated_button)
        {
            case 101://Choice 1 selected
                {
                    ;
                }
            break;
            case 102://Choice 2 selected
                {
                    ;
                }
            break;
            case 103://Choice 3 selected
                {
                    ;
                }
            break;
            case 104://Choice 4 selected
                {
                    ;
                }
            break;
            case 105://Choice 5 selected
                {
                    ;
                }
            break;
            case 4001://left arrow on button 1
                {
                    ;
                }
            break;
            case 5001://right arrow on button 1
                {
                    ;
                }
            break;
            case 3://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.log.File_Write("Entering main menu, from New_Game menu. - button selected.");
            break;
            case 65533://menu choice changed
                sound.menu_move_00.play();
            break;
            case 65534://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.io.escape               = false;
                game.log.File_Write("Entering main menu, from New_Game menu. - escape preses.");
            break;
            case 65535://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.log.File_Write("Entering main menu, from New_Game menu. - button clicked.");
            break;
            default:
            break;
        };
    };
    // ------------------- Load menu ------------
    activated_button = -1;
    if (game.menu_level == 3)
    {
        activated_button = load_menu.process();
        switch (activated_button)
        {
            case 1://Save Slot 1 selected.
                if (load_menu.get_button_enabled(1))
                {
                    game.save_01.Assign_File("save/slot_01.sav");
                    if (game.save_01.Load())
                    {
                        game.log.File_Write("Loading from slot 1");
                        //game_o.loaded.spawn();
                        game.game_active = true;
                        game.menu_active = false;
                        game.log.File_Write("Resuming game");
                        game.music_next_track = true;
                        sound.menu_select_00.play();
                    }
                }
            break;
            case 2://Save Slot 2 selected.
                if (load_menu.get_button_enabled(2))
                {
                    game.save_02.Assign_File("save/slot_02.sav");
                    if (game.save_02.Load())
                    {
                        game.log.File_Write("Loading from slot 2");
                        //game_o.loaded.spawn();
                        game.game_active = true;
                        game.menu_active = false;
                        game.log.File_Write("Resuming game");
                        game.music_next_track = true;
                        sound.menu_select_00.play();
                    }
                }
            break;
            case 3://Save Slot 3 selected.
                if (load_menu.get_button_enabled(3))
                {
                    game.save_03.Assign_File("save/slot_03.sav");
                    if (game.save_03.Load())
                    {
                        game.log.File_Write("Loading from slot 3");
                        //game_o.loaded.spawn();
                        game.game_active = true;
                        game.menu_active = false;
                        game.log.File_Write("Resuming game");
                        game.music_next_track = true;
                        sound.menu_select_00.play();
                    }
                }
            break;
            case 4://Save Slot 4 selected.
                if (load_menu.get_button_enabled(4))
                {
                    game.save_04.Assign_File("save/slot_04.sav");
                    if (game.save_04.Load())
                    {
                        game.log.File_Write("Loading from slot 4");
                        //game_o.loaded.spawn();
                        game.game_active = true;
                        game.menu_active = false;
                        game.log.File_Write("Resuming game");
                        game.music_next_track = true;
                        sound.menu_select_00.play();
                    }
                }
            break;
            case 5://Save Slot 5 selected.
                if (load_menu.get_button_enabled(5))
                {
                    game.save_05.Assign_File("save/slot_05.sav");
                    if (game.save_05.Load())
                    {
                        game.log.File_Write("Loading from slot 5");
                        //game_o.loaded.spawn();
                        game.game_active = true;
                        game.menu_active = false;
                        game.log.File_Write("Resuming game");
                        game.music_next_track = true;
                        sound.menu_select_00.play();
                    }
                }
            break;
            case 6://Save Slot 6 selected.
                if (load_menu.get_button_enabled(6))
                {
                    game.save_06.Assign_File("save/slot_06.sav");
                    if (game.save_06.Load())
                    {
                        game.log.File_Write("Loading from slot 6");
                        //game_o.loaded.spawn();
                        game.game_active = true;
                        game.menu_active = false;
                        game.log.File_Write("Resuming game");
                        game.music_next_track = true;
                        sound.menu_select_00.play();
                    }
                }
            break;
            case 7://Save Slot 7 selected.
                if (load_menu.get_button_enabled(7))
                {
                    game.save_07.Assign_File("save/slot_07.sav");
                    if (game.save_07.Load())
                    {
                        game.log.File_Write("Loading from slot 7");
                        //game_o.loaded.spawn();
                        game.game_active = true;
                        game.menu_active = false;
                        game.log.File_Write("Resuming game");
                        game.music_next_track = true;
                        sound.menu_select_00.play();
                    }
                }
            break;
            case 9://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.log.File_Write("Entering main menu, from load menu. - button selected.");
            break;
            case 65533://menu choice changed
                sound.menu_move_00.play();
            break;
            case 65534://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.io.escape               = false;
                game.log.File_Write("Entering main menu, from load menu. - escape preses.");
            break;
            case 65535://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.log.File_Write("Entering main menu, from load menu. - button clicked.");
            break;
            default:
            break;
        };
    };
    // ------------------- Save menu ------------
    activated_button = -1;
    if (game.menu_level == 4)
    {
        activated_button = save_menu.process();
        switch (activated_button)
        {
            case 1://Save Slot 1 selected.
                game.save_01.Assign_File("save/slot_01.sav");
                game.save_01.Save();
                game.log.File_Write("Saving to slot 1");
                //game_o.saved.spawn();
                game.game_active = true;
                game.menu_active = false;
                game.log.File_Write("Resuming game");
                game.music_next_track = true;
                sound.menu_select_00.play();
                load_menu.button[1].set_enabled(true);
            break;
            case 2://Save Slot 2 selected.
                game.save_02.Assign_File("save/slot_02.sav");
                game.save_02.Save();
                game.log.File_Write("Saving to slot 2");
                //game_o.saved.spawn();
                game.game_active = true;
                game.menu_active = false;
                game.log.File_Write("Resuming game");
                game.music_next_track = true;
                sound.menu_select_00.play();
                load_menu.button[2].set_enabled(true);
            break;
            case 3://Save Slot 3 selected.
                game.save_03.Assign_File("save/slot_03.sav");
                game.save_03.Save();
                game.log.File_Write("Saving to slot 3");
                //game_o.saved.spawn();
                game.game_active = true;
                game.menu_active = false;
                game.log.File_Write("Resuming game");
                game.music_next_track = true;
                sound.menu_select_00.play();
                load_menu.button[3].set_enabled(true);
            break;
            case 4://Save Slot 4 selected.
                game.save_04.Assign_File("save/slot_04.sav");
                game.save_04.Save();
                game.log.File_Write("Saving to slot 4");
                //game_o.saved.spawn();
                game.game_active = true;
                game.menu_active = false;
                game.log.File_Write("Resuming game");
                game.music_next_track = true;
                sound.menu_select_00.play();
                load_menu.button[4].set_enabled(true);
            break;
            case 5://Save Slot 5 selected.
                game.save_05.Assign_File("save/slot_05.sav");
                game.save_05.Save();
                game.log.File_Write("Saving to slot 5");
                //game_o.saved.spawn();
                game.game_active = true;
                game.menu_active = false;
                game.log.File_Write("Resuming game");
                game.music_next_track = true;
                sound.menu_select_00.play();
                load_menu.button[5].set_enabled(true);
            break;
            case 6://Save Slot 6 selected.
                game.save_06.Assign_File("save/slot_06.sav");
                game.save_06.Save();
                game.log.File_Write("Saving to slot 6");
                //game_o.saved.spawn();
                game.game_active = true;
                game.menu_active = false;
                game.log.File_Write("Resuming game");
                game.music_next_track = true;
                sound.menu_select_00.play();
                load_menu.button[6].set_enabled(true);
            break;
            case 7://Save Slot 7 selected.
                game.save_07.Assign_File("save/slot_07.sav");
                game.save_07.Save();
                game.log.File_Write("Saving to slot 7");
                //game_o.saved.spawn();
                game.game_active = true;
                game.menu_active = false;
                game.log.File_Write("Resuming game");
                game.music_next_track = true;
                sound.menu_select_00.play();
                load_menu.button[7].set_enabled(true);
            break;
            case 9://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.log.File_Write("Entering main menu, from save menu. - button selected.");
            break;
            case 65533://menu choice changed
                sound.menu_move_00.play();
            break;
            case 65534://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.io.escape               = false;
                game.log.File_Write("Entering main menu, from save menu. - escape preses.");
            break;
            case 65535://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.log.File_Write("Entering main menu, from save menu. - button clicked.");
            break;
            default:
            break;
        };
    };
    // ------------------- Options Menu ------------
    activated_button = -1;
    if (game.menu_level == 5)
    {
        options_menu.set_toggle_data(4,game.config.Display_Fullscreen);
        activated_button = options_menu.process();
        options_menu.set_button_current_choice(3,game.config.Display_resolution-1);
        switch (activated_button)
        {
            case 4://Toggle Full-screen
                options_menu.set_toggle_data(4,!options_menu.get_toggle_data(4));
                game.config.Display_Fullscreen   = !game.config.Display_Fullscreen;
                if (game.config.Display_Fullscreen) SDL_SetVideoMode(game.config.Display_X_Resolution,game.config.Display_Y_Resolution,game.config.Display_BPS,SDL_OPENGL | SDL_FULLSCREEN);
                else                                SDL_SetVideoMode(game.config.Display_X_Resolution,game.config.Display_Y_Resolution,game.config.Display_BPS,SDL_OPENGL);
                game.graphics.init_gl(game.config.Display_X_Resolution,game.config.Display_Y_Resolution);
                load_textures();
            break;
            case 301://Choice 1 selected
                if (game.config.Display_resolution != options_menu.get_button_choice_position(3) + 0 -1)
                {
                    game.config.Display_resolution = options_menu.get_button_choice_position(3) + 0 -1;
                    set_resolution = true;
                }
            break;
            case 302://Choice 2 selected
                if (game.config.Display_resolution != options_menu.get_button_choice_position(3) + 1 -1)
                {
                    game.config.Display_resolution = options_menu.get_button_choice_position(3) + 1 -1;
                    set_resolution = true;
                }
            break;
            case 303://Choice 3 selected
                if (game.config.Display_resolution != options_menu.get_button_choice_position(3) + 2 -1)
                {
                    game.config.Display_resolution = options_menu.get_button_choice_position(3) + 2 -1;
                    set_resolution = true;
                }
            break;
            case 304://Choice 4 selected
                if (game.config.Display_resolution != options_menu.get_button_choice_position(3) + 3 -1)
                {
                    game.config.Display_resolution = options_menu.get_button_choice_position(3) + 3 -1;
                    set_resolution = true;
                }
            break;
            case 305://Choice 5 selected
                if (game.config.Display_resolution != options_menu.get_button_choice_position(3) + 4 -1)
                {
                    game.config.Display_resolution = options_menu.get_button_choice_position(3) + 4 -1;
                    set_resolution = true;
                }
            break;
            case 4001://left arrow on button 1
                game.config.Audio_Sound_Volume --;
                if (game.config.Audio_Sound_Volume < 0) game.config.Audio_Sound_Volume = 0;
                Mix_Volume(-1,game.config.Audio_Sound_Volume);
                options_menu.set_button_slider_position(1,game.config.Audio_Sound_Volume);
            break;
            case 5001://right arrow on button 1
                game.config.Audio_Sound_Volume++;
                if (game.config.Audio_Sound_Volume > 128) game.config.Audio_Sound_Volume = 128;
                Mix_Volume(-1,game.config.Audio_Sound_Volume);
                options_menu.set_button_slider_position(1,game.config.Audio_Sound_Volume);
            break;
            case 4002://left arrow on button 2
                game.config.Audio_Music_Volume--;
                if (game.config.Audio_Music_Volume < 0) game.config.Audio_Music_Volume = 0;
                Mix_VolumeMusic(game.config.Audio_Music_Volume);
                options_menu.set_button_slider_position(2,game.config.Audio_Music_Volume);
            break;
            case 5002://right arrow on button 2
                game.config.Audio_Music_Volume++;
                if (game.config.Audio_Music_Volume > 128) game.config.Audio_Music_Volume = 128;
                Mix_VolumeMusic(game.config.Audio_Music_Volume);
                options_menu.set_button_slider_position(2,game.config.Audio_Music_Volume);
            break;
            case 4003://left arrow on button 3
                options_menu.set_button_choice_position(3,options_menu.get_button_choice_position(3)-1);
                if (options_menu.get_button_choice_position(3) < 1) options_menu.set_button_choice_position(3,1);
            break;
            case 5003://right arrow on button 3
                options_menu.set_button_choice_position(3,options_menu.get_button_choice_position(3)+1);
                if (options_menu.get_button_choice_position(3) >= options_menu.get_number_of_choices(3)-(options_menu.get_number_of_visible_choices(3)-1)) options_menu.set_button_choice_position(3,options_menu.get_number_of_choices(3)-(options_menu.get_number_of_visible_choices(3)-1));
            break;
            case 6://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.log.File_Write("Entering main menu, from Options menu. - button selected.");
            break;
            case 65533://menu choice changed
                sound.menu_move_00.play();
            break;
            case 65534://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.io.escape               = false;
                game.log.File_Write("Entering main menu, from Options menu. - escape preses.");
            break;
            case 65535://Return to main menu
                sound.menu_select_00.play();
                game.menu_level = 1;
                game.log.File_Write("Entering main menu, from Options menu. - button clicked.");
            break;
            default:
            break;
        };
        if (set_resolution)
        {
            set_resolution = false;
            if (game.config.Display_resolution == 0)
            {
                game.config.Display_X_Resolution = 640;
                game.config.Display_Y_Resolution = 480;
            }
            if (game.config.Display_resolution == 1)
            {
                game.config.Display_X_Resolution = 800;
                game.config.Display_Y_Resolution = 600;
            }
            if (game.config.Display_resolution == 2)
            {
                game.config.Display_X_Resolution = 1024;
                game.config.Display_Y_Resolution = 768;
            }
            if (game.config.Display_resolution == 3)
            {
                game.config.Display_X_Resolution = 1280;
                game.config.Display_Y_Resolution = 1024;
            }
            if (game.config.Display_resolution == 4)
            {
                game.config.Display_X_Resolution = 1366;
                game.config.Display_Y_Resolution = 768;
            }
            if (game.config.Display_resolution == 5)
            {
                game.config.Display_X_Resolution = 1440;
                game.config.Display_Y_Resolution = 900;
            }
            if (game.config.Display_resolution == 6)
            {
                game.config.Display_X_Resolution = 1680;
                game.config.Display_Y_Resolution = 1050;
            }
            if (game.config.Display_resolution == 7)
            {
                game.config.Display_X_Resolution = 1920;
                game.config.Display_Y_Resolution = 1080;
            }
            game.config.mouse_resolution_x   = game.config.Display_X_Resolution;
            game.config.mouse_resolution_y   = game.config.Display_Y_Resolution;
            if (game.config.Display_Fullscreen) SDL_SetVideoMode(game.config.Display_X_Resolution,game.config.Display_Y_Resolution,game.config.Display_BPS,SDL_OPENGL | SDL_FULLSCREEN);
            else                                SDL_SetVideoMode(game.config.Display_X_Resolution,game.config.Display_Y_Resolution,game.config.Display_BPS,SDL_OPENGL);
            game.graphics.init_gl(game.config.Display_X_Resolution,game.config.Display_Y_Resolution);
            load_textures();
        }
    };
    // ------------------- Game Over Menu ------------
    activated_button = -1;
    if (game.menu_level == 6)
    {
        activated_button = game_over_menu.process();
        switch (activated_button)
        {
            case 1://Button 1 selected.
                sound.menu_select_00.play();
                game.menu_level              = 1;
                game.menu_active             = true;
                game.pdie_active             = false;
                game.outr_active             = false;
                game.game_active             = false;
                game.nlvl_active             = false;
                game.io.escape               = false;
                game.music_next_track        = true;
                game.log.File_Write("Entering main menu, from game over menu. - button 1 selected.");
                main_menu.set_keyboard_delay_count(0);
                main_menu.set_mouse_delay_count(0);
                SDL_WarpMouse(game.graphics.gl_to_res(main_menu.get_button_x_pos(1),game.config.mouse_resolution_x),game.config.mouse_resolution_y-game.graphics.gl_to_res(main_menu.get_button_y_pos(1),game.config.mouse_resolution_y));
            break;
            case 65533://menu choice changed
                sound.menu_move_00.play();
            break;
            case 65534://Return to main menu
                sound.menu_select_00.play();
                game.menu_level              = 1;
                game.menu_active             = true;
                game.pdie_active             = false;
                game.outr_active             = false;
                game.game_active             = false;
                game.nlvl_active             = false;
                game.io.escape               = false;
                game.music_next_track        = true;
                game.log.File_Write("Entering main menu, from game over menu. - button 1 selected.");
                main_menu.set_keyboard_delay_count(0);
                main_menu.set_mouse_delay_count(0);
                SDL_WarpMouse(game.graphics.gl_to_res(main_menu.get_button_x_pos(1),game.config.mouse_resolution_x),game.config.mouse_resolution_y-game.graphics.gl_to_res(main_menu.get_button_y_pos(1),game.config.mouse_resolution_y));
            break;
            case 65535://Return to main menu
                sound.menu_select_00.play();
                game.menu_level              = 1;
                game.menu_active             = true;
                game.pdie_active             = false;
                game.outr_active             = false;
                game.game_active             = false;
                game.nlvl_active             = false;
                game.io.escape               = false;
                game.music_next_track        = true;
                game.log.File_Write("Entering main menu, from game over menu. - button 1 selected.");
                main_menu.set_keyboard_delay_count(0);
                main_menu.set_mouse_delay_count(0);
                SDL_WarpMouse(game.graphics.gl_to_res(main_menu.get_button_x_pos(1),game.config.mouse_resolution_x),game.config.mouse_resolution_y-game.graphics.gl_to_res(main_menu.get_button_y_pos(1),game.config.mouse_resolution_y));
            break;
            default:
            break;
        };
    };
    // ------------------- Pause Menu ------------
    activated_button = -1;
    if (game.menu_level == 7)
    {
        activated_button = pause_menu.process();
        switch (activated_button)
        {
            case 1://Button 1 selected.
                sound.menu_select_00.play();
                game.game_paused      = false;
                game.game_active      = true;
                game.io.escape        = false;
                game.io.select        = false;
                game.io.pause         = false;
                SDL_WarpMouse(game.graphics.gl_to_res(main_menu.get_button_x_pos(1),game.config.mouse_resolution_x),game.config.mouse_resolution_y-game.graphics.gl_to_res(main_menu.get_button_y_pos(1),game.config.mouse_resolution_y));
                game.io.space  = false;
                game.io.enter  = false;
                game.io.select = false;
                main_menu.set_keyboard_delay(128);
                main_menu.set_keyboard_delay_count(0);
                main_menu.set_mouse_delay_count(0);
                game.log.File_Write("Entering game menu, from pause menu. - button 1 selected.");
            break;
            case 65533://menu choice changed
                sound.menu_move_00.play();
            break;
            case 65534://Return to game
                sound.menu_select_00.play();
                game.game_paused      = false;
                game.game_active      = true;
                game.io.escape        = false;
                game.io.select        = false;
                game.io.pause         = false;
                SDL_WarpMouse(game.graphics.gl_to_res(main_menu.get_button_x_pos(1),game.config.mouse_resolution_x),game.config.mouse_resolution_y-game.graphics.gl_to_res(main_menu.get_button_y_pos(1),game.config.mouse_resolution_y));
                game.io.space  = false;
                game.io.enter  = false;
                game.io.select = false;
                main_menu.set_keyboard_delay(128);
                main_menu.set_keyboard_delay_count(0);
                main_menu.set_mouse_delay_count(0);
                game.log.File_Write("Entering game menu, from pause menu. - button 1 selected.");
            break;
            case 65535://Return to game
                sound.menu_select_00.play();
                game.game_paused      = false;
                game.game_active      = true;
                game.io.escape        = false;
                game.io.select        = false;
                game.io.pause         = false;
                SDL_WarpMouse(game.graphics.gl_to_res(main_menu.get_button_x_pos(1),game.config.mouse_resolution_x),game.config.mouse_resolution_y-game.graphics.gl_to_res(main_menu.get_button_y_pos(1),game.config.mouse_resolution_y));
                game.io.space  = false;
                game.io.enter  = false;
                game.io.select = false;
                main_menu.set_keyboard_delay(128);
                main_menu.set_keyboard_delay_count(0);
                main_menu.set_mouse_delay_count(0);
                game.log.File_Write("Entering game menu, from pause menu. - button 1 selected.");
            break;
            default:
            break;
        };
    };
    //-------------------------------------------------------------------------------------------------------------------
   return(0);
};

//---------------------------------------------------------------------------------------------------------------
int diplay_menu (void)
{
    glPushMatrix();
    glDisable(GL_DEPTH_TEST);
    if (game.menu_level !=  7)
    {
        game.background.draw();
    }
    font.font_1.Write(255,255,255,64,-0.98f,-0.98f,2,8,"www.PhysHexGames.co.nr");
/*-----------------------------------------------------------------------------*/
   if (game.menu_level ==  7) //Pause screen
   {
   }
/*-----------------------------------------------------------------------------*/
   if (game.menu_level ==  1) main_menu.draw();//main_menu
   if (game.menu_level ==  2) new_game_menu.draw();//new_game_menu
   if (game.menu_level ==  3) load_menu.draw();//load_menu
   if (game.menu_level ==  4) save_menu.draw();//save_menu
   if (game.menu_level ==  5) options_menu.draw();//options_menu
   if (game.menu_level ==  6) game_over_menu.draw();//game_over_menu
   if (game.menu_level ==  7) pause_menu.draw(); //pause_menu
/*-----------------------------------------------------------------------------*/
   glPopMatrix();
   return(0);
};
